baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Until a good name is found'
theme = ["PaperModX"]
font_size = 18
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  ShowReadingTime = true
  ShowShareButtons =  true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  math = true
  showtoc = true
  tocopen = true
  TocSide = "left"
  hideSummary = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'